# Generated by Django 2.0.4 on 2018-06-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='std_reason',
            field=models.TextField(null=True, verbose_name='标准文本理由'),
        ),
    ]
