# Generated by Django 2.0.3 on 2018-04-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='x_frame_options',
            field=models.CharField(default='', max_length=255, verbose_name='iframe加载问题'),
        ),
        migrations.AddField(
            model_name='rule',
            name='freq_ans',
            field=models.TextField(null=True, verbose_name='不通过的常规答案'),
        ),
    ]
