# Generated by Django 2.0.3 on 2018-04-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20180424_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='网站id'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='网页id'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='检测规则id'),
        ),
    ]
