# Generated by Django 2.0.3 on 2018-04-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20180429_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='check_method',
            field=models.TextField(null=True, verbose_name='检测方法说明'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.TextField(null=True, verbose_name='规则说明'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='pass_condition',
            field=models.TextField(null=True, verbose_name='通过条件说明'),
        ),
    ]
