# Generated by Django 2.0.3 on 2018-04-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20180429_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='applicant',
        ),
    ]
