# Generated by Django 2.0.3 on 2018-04-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_remove_host_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='local_dir',
            field=models.CharField(max_length=255, null=True, verbose_name='本地地址'),
        ),
        migrations.AlterField(
            model_name='page',
            name='x_frame_options',
            field=models.CharField(max_length=255, null=True, verbose_name='iframe加载问题'),
        ),
    ]
