# Generated by Django 2.0.3 on 2018-05-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20180429_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='property',
            field=models.CharField(max_length=20, null=True, verbose_name='属性'),
        ),
        migrations.AlterField(
            model_name='page',
            name='local_dir',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='本地地址'),
        ),
        migrations.AlterField(
            model_name='page',
            name='x_frame_options',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='iframe加载问题'),
        ),
    ]
