# Generated by Django 2.0.3 on 2018-04-18 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='学习项id')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('page_id', models.IntegerField(verbose_name='网页id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='学习记录id')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('item_id', models.IntegerField(verbose_name='学习项id')),
                ('rule_id', models.IntegerField(verbose_name='规则id')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('user_result', models.IntegerField(choices=[(0, '不通过'), (1, '通过'), (2, '不存在'), (3, '不知道')], verbose_name='用户答案')),
                ('std_result', models.IntegerField(choices=[(0, '不通过'), (1, '通过'), (2, '不存在'), (3, '不知道')], verbose_name='标准答案')),
                ('judge', models.IntegerField(choices=[(0, '用户答案与标答不一致'), (1, '用户答案与标答一致')], verbose_name='用户答案判断')),
                ('reason', models.TextField(verbose_name='用户给出的理由')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
