# Generated by Django 2.0.3 on 2018-05-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningsystem', '0003_auto_20180429_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='item_id',
        ),
        migrations.AddField(
            model_name='record',
            name='page_id',
            field=models.IntegerField(null=True, verbose_name='网页id'),
        ),
    ]
