# Generated by Django 2.0.3 on 2018-05-27 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learningsystem', '0004_auto_20180501_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='reason_tag',
        ),
        migrations.AddField(
            model_name='record',
            name='change_count',
            field=models.IntegerField(default=0, verbose_name='答案的切换次数'),
        ),
        migrations.AddField(
            model_name='record',
            name='finish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='任务结束的时间'),
        ),
        migrations.AddField(
            model_name='record',
            name='reason_images',
            field=models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='用户上传的图片理由'),
        ),
        migrations.AddField(
            model_name='record',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请任务的时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='reason',
            field=models.TextField(null=True, verbose_name='用户给出的文本理由'),
        ),
    ]
